# Generated by Django 4.1.3 on 2022-11-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_last_names_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_in',
            new_name='Check_InDate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_out',
            new_name='Check_OutDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_Guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
