# Generated by Django 4.1.3 on 2022-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_menu_remove_room_price_room_breakfast_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='breakfast_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='fullboard_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='halfboard_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_with_AC',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_without_AC',
            field=models.FloatField(default=0),
        ),
    ]
