# Generated by Django 4.1.2 on 2022-11-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactmessage_update_category_update_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_image',
            old_name='room',
            new_name='service',
        ),
    ]
